### ISSUE TITLE
下载了您的架构，但是本地运行总是报错，纠结ing

### ISSUE THREAD

**Issue by 811722066** [goodspb/elcon#1]
common\Log.php on line 35
提示
ErrorException: 2 - Cannot bind an instance to a static closure；
找不到原因好着急啊！

**Comment by goodspb** [comment]
不好意思，信息不太够，不能定位发生了什么。
请检查：phalcon 是否安装？版本号是多少？
请尝试：composer dump-autoload 一次

**Comment by 811722066** [comment]
非常感谢您的回复， 好激动； 是在windows环境下，php版本是5.5.12，phalcon版本是2.1.0 32位的；
我尝试了好几次， 在家在公司都试了，完全根据您上面的提示安装的 ，composer命令也执行了，但是都是在Log文件的第35行报错，提示就是不能给静态方法上绑定实例；
看了您的架构， 虽然我的水平还差很远， 但是思想上觉得很合理，所以很希望能了解您的架构！

**Comment by goodspb** [comment]
嘿嘿，其实我水平也是有限啦。
你这个问题可能是 Phalcon 版本 和 PHP 版本不相容的问题，具体可以看：https://github.com/phalcon/cphalcon/issues/11029

解决方法：使用 Phalcon 2.0.x 版本的吧。

**Comment by 811722066** [comment]
好的 ， 谢谢啦， 我再看看！
